################################################################################

# Copyright (c) 2026, Tinker Twins, AutoDRIVE Ecosystem
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

################################################################################

/**:
  ros__parameters:
    ############################################################################
    # FILTER TIMING AND MOTION MODEL
    ############################################################################

    frequency: 20.0     # Frequency (Hz) at which filter will output estimates
    sensor_timeout: 0.1 # Period (seconds) after which we consider a sensor to have timed out
    two_d_mode: true    # Whether to operate with a planar 2D assumption/constraint

    ############################################################################
    # TRANSFORM TIMING
    ############################################################################

    transform_time_offset: 0.1  # Temporal offset to the transform generated by the filter
    transform_timeout: 0.0      # Period (seconds) after which we consider transform to have timed out

    ############################################################################
    # DIAGNOSTICS
    ############################################################################

    print_diagnostics: false    # Whether to publish diagnostics to /diagnostics_agg topic
    debug: false                # Whether to output debugging information (can reduce performance)
    debug_out_file: /path/to/debug/file.txt # Please specify the full path

    ############################################################################
    # STATE PUBLICATION
    ############################################################################

    publish_acceleration: false     # Whether to publish the acceleration state
    publish_tf: true                # Whether to broadcast the transformation over the /tf topic
    predict_to_current_time: true   # Whether to extrapolate state from the last measurement time

    ############################################################################
    # COORDINATE FRAMES
    ############################################################################

    # REP-105 (http://www.ros.org/reps/rep-0105.html) specification is used
    world_frame: odom                   # World frame
    map_frame: map                      # Map frame
    odom_frame: odom                    # Odometry frame
    base_link_frame: base_footprint     # Robot base frame

    ############################################################################
    # ODOMETRY INPUT
    ############################################################################

    # The filter accepts an arbitrary number of inputs from each input type
    odom0: odom # Configure input of type nav_msgs/Odometry

    # Each sensor reading updates some or all of the filter's state
    odom0_config: [true,  true,  true,      # x, y, z
                   true,  true,  true,      # roll, pitch, yaw
                   true,  true,  true,      # vx, vy, vz
                   false, false, false,     # vroll, vpitch, vyaw
                   false, false, false]     # ax, ay, az
    
    odom0_queue_size: 10        # Size of the subscription queue so that more measurements are fused
    odom0_nodelay: true         # Whether to use the tcpNoDelay option (disable Nagle's algorithm)
    odom0_differential: false   # Whether to use differential mode on absolute pose data
    odom0_relative: false       # Whether first measurement is treated as a "zero point"

    ############################################################################
    # IMU INPUT
    ############################################################################

    # The filter accepts an arbitrary number of inputs from each input type
    imu0: imu_filter    # Configure input of type sensor_msgs/Imu

    # Each sensor reading updates some or all of the filter's state
    imu0_config: [false, false, false,      # x, y, z
                  true,  true,  true,       # roll, pitch, yaw
                  false, false, false,      # vx, vy, vz
                  true,  true,  true,       # vroll, vpitch, vyaw
                  true,  true,  true]       # ax, ay, az

    imu0_queue_size: 10         # Size of the subscription queue so that more measurements are fused
    imu0_nodelay: true          # Whether to use the tcpNoDelay option (disable Nagle's algorithm)
    imu0_differential: false    # Whether to use differential mode on absolute pose data
    imu0_relative: false        # Whether first measurement is treated as a "zero point"

    # Whether to apply gravity compensation (if IMU data includes acceleration due to gravity)
    imu0_remove_gravitational_acceleration: true

    ############################################################################
    # PROCESS NOISE COVARIANCE
    ############################################################################

    # The principal diagonal values are ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.06, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
                               0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
    ############################################################################
    # INITIAL ESTIMATE COVARIANCE
    ############################################################################

    # The principal diagonal values are ordered as x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az
    initial_estimate_covariance: [1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9, 0.0,     0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    1e-9,  0.0,     0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     1e-9,  0.0,     0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     1e-9,  0.0,    0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     1e-9, 0.0,    0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    1e-9, 0.0,
                                  0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,     0.0,    0.0,    1e-9]
