DROP TABLE IF EXISTS Vehicles;
DROP TABLE IF EXISTS TrafficSigns;
DROP TABLE IF EXISTS TrafficLights;

CREATE TABLE Vehicles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    posX FLOAT NOT NULL,
    posY FLOAT NOT NULL,
    yaw FLOAT NOT NULL
);

CREATE TABLE TrafficSigns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    posX FLOAT NOT NULL,
    posY FLOAT NOT NULL,
    name TEXT NOT NULL
);


CREATE TABLE TrafficLights (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    posX FLOAT NOT NULL,
    posY FLOAT NOT NULL,
    status TEXT NOT NULL
);
